### ISSUE TITLE
Hello can not be resolved to a type

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#267]
```
@{
  class Hello {
    String hello="Hello";
  }
  Hello hello=new Hello();
}
@def sayHello(Hello hello) {
  @hello.hello
}
@hello.hello
@sayHello()
```

this is a very important feature

**Comment by greenlaw110** [comment]
Your template needs a little bit update. Checkout http://fiddle.rythmengine.org/#/editor/18af81d8a5d1412da6945760ae92a103

**Comment by WolfgangFahl** [comment]
It would be very helpful to simplify the syntax and remove the unneccessary @def. 
Adding the @def makes the code hard to read, cut&paste is more difficult and there is another thing that needs explanation. If you simply parse the class as if it had @def we are all set.

**Comment by greenlaw110** [comment]
@WolfgangFahl there are two things actually:

1. The `@{ }` marks an inline code block in the render method, meaning everything defined inside it belongs to the method runtime scope including the classes defined inside it. While `@def class <ClassName> {}` clearly define something that is outside of the render method scope, which means the class defined with the leading directive `@def class` is a static inner class of the template. Semantically it clearly differentiate the two things in terms of scope.

2. Your code confuse the operating scopes by trying to refer the inner class defined in the render method from another class method, in your example `sayHello` which is defined again by the `@def` directive. That's why it complain that `Hello` class is not found.

Aesthetically I wouldn't accept the solution that take `class` definition out of the `@{}` block and treat it as a static inner class of the template class. Sorry about that.

**Comment by WolfgangFahl** [comment]
an common ground might be 
@dev package A {
  class A {
  }
  class B {
  }
}
or
@dev java {
class something {
}
or
class another {
}
}
@dev code {
class C1 {
}
class C2 {
}
}

Currently for each class the @def has to be removed when debugging the content in a Java IDE. Also it's not possible to share the code between a JAVA IDE and Rythm. This is especially bad for the testability of the code. I'd rather test the code in a jenkins/maven/Eclipse environment and than use it as is within ryhthm then have to debug the code right in the Rythm environment. So it's not only about aesthetics. Not touching the Java code at all and being as Java compatible as possible are very important design goals from my point of view.

**Comment by greenlaw110** [comment]
I see where you come from now. I will try to work out something for you this weekend

**Comment by WolfgangFahl** [comment]
This is very good news indeed. I am looking forward to the results.

**Comment by greenlaw110** [comment]
My apologize I missed the work last week coz the heavy work load from the company. Will catch up this week and keep you updated

**Comment by greenlaw110** [comment]
See #271: Allow template author to add arbitrary code at class level

**Comment by greenlaw110** [comment]
@WolfgangFahl can we close this issue now?
